version: "2"
services: 
  mysql: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
volumes:
  ./mysql/db